### PR TITLE
update to cosas 0.8

### PR DESCRIPTION
**Pull request by eparejatobes**

### CODE REVIEW

**Comment by laughedelic** [comment]
are you working on this?

**Comment by eparejatobes** [comment]
yes, give me a sec

**Comment by eparejatobes** [comment]
@laughedelic everything compiles now including the tests. The part about denotations of input and output records can improved.

**Comment by eparejatobes** [comment]
You are more familiar with loquat :) so better that you finish this

**Comment by laughedelic** [comment]
Ok. I'm going to review it now

**Comment by eparejatobes** [comment]
How to infer the subtypes of input/output Raws

1. pass processData as a function from (InputFiles, Context) to Instructions[OutputFiles] (:+1: from me for this option)
2. make parsing in cosas a bit more generic so that it will work with record.Raw directly

**Comment by eparejatobes** [comment]
well 1. doesn't make sense :)

**Pull request merged**
