### PR TITLE
Working with S3 directories

### PR DESCRIPTION
**Pull request by laughedelic**

### CODE REVIEW

**Comment by laughedelic** [comment]
Published under `2.0.0-SNAPSHOT`. It shouldn't brake things that already use it.

**Comment by eparejatobes** [comment]
https://github.com/ohnosequences/loquat/pull/7#issuecomment-141232236 what do you mean with checking if it is a folder?

**Comment by laughedelic** [comment]
I mean that I supposed that there is an API to check that certain S3 key-prefix exists. Now I think that I could list objects for that...

**Comment by eparejatobes** [comment]
yes, just list bucket with prefix and limit results. What should be clear is the expected behavior. It's not as straightforward as it could look

**Comment by laughedelic** [comment]
What do you mean by limiting results? "_

**Comment by eparejatobes** [comment]
when listing

**Pull request merged**
