### PR TITLE
A release based on cosas 0.8.0

### PR DESCRIPTION
**Pull request by laughedelic**
@laughedelic I want to make such a release :) what would be the right starting point? any low hanging fruit somewhere in a branch here?

### CODE REVIEW

**Comment by laughedelic** [comment]
@eparejatobes it was super-easy. Merging?

**Comment by eparejatobes** [comment]
I know be55ba2928e7c7f322d80886394a867455a1cc7b :tong

**Comment by laughedelic** [comment]
:hushed: :speak_no_evil:

**Comment by eparejatobes** [comment]
:laug

**Comment by laughedelic** [comment]
So then what's the question? you want a release with it?
There is https://github.com/ohnosequences/loquat/issues/36, it's not crucial, but would be nice to fix before release.

**Comment by eparejatobes** [comment]
Let's just make a new milestone then

**Comment by laughedelic** [comment]
Done: https://github.com/ohnosequences/loquat/releases/tag/v2.0.0-M5

**Comment by eparejatobes** [comment]
:

**Pull request closed without merging**
