### PR TITLE
Sending tasks to the input SQS in parallel

### PR DESCRIPTION
**Pull request by eparejatobes**

### CODE REVIEW

**Comment by eparejatobes** [comment]
It's easy to get 1000 mssgs/s. I will fix ohnosequences/aws-scala-tools#46 and then add this to the worker code

**Comment by eparejatobes** [comment]
Also having batch send should give a 10x increase

**Comment by eparejatobes** [comment]
I've done some casual testing on EC2, and on an `m4.xlarge` we get a sustained `4000 mssg/s` with around 400 threads and connections.

I think it worthwhile to pick by default an instance type with network performance *High*.

**Comment by laughedelic** [comment]
> I think it worthwhile to pick by default an instance type with network performance High.

I think that the manager instance should be the simplest/cheapest one. It's not a big difference, if the initialisation will take 10 seconds or a minute, but this instance is going to be on during the whole time. So if workers will be processing tasks for 20 hours, you're going to pay for this fancy manager doing nothing.

**Comment by laughedelic** [comment]
I'm going to release M8 with what we have at the moment to have some stable tested loquat version. This is going to the next release.

**Comment by laughedelic** [comment]
This is mostly done in 149673169d6f0fb322c863101088e505b2541f38 (not polished, but should work)

**Pull request closed without merging**
